version: '3'
services:
    # web-build:
    #     build: app
    #     image: demo-app:latest
    # web1:
    #     image: demo-app:latest
    #     ports:
    #         - "5000:5000"
    # web2:
    #     image: demo-app:latest
    #     ports:
    #         - "5001:5000"
    # web3:
    #     image: demo-app:latest
    #     ports:
    #         - "5002:5000"
    nginx-build:
        build: nginx
        image: demo-nginx:latest
    nginx-loadbalancer:
        image: demo-nginx:latest
        ports:
            - "81:80"
