---
version: '3'
services:
    web-build:
        build: app
        image: demo-app:latest
        environment:
            - REDIS_IP=10.5.0.6
            - REDIS_PORT=6379
    redis:
        build: redis
        ports:
            - "6379:6379"
        networks:
            vpc:
                ipv4_address: 10.5.0.6
    web1:
        image: demo-app:latest
        ports:
            - "5000:5000"
        environment:
            - REDIS_IP=10.5.0.6
            - REDIS_PORT=6379
        networks:
            vpc:
                ipv4_address: 10.5.0.2
    web2:
        image: demo-app:latest
        ports:
            - "5001:5000"
        environment:
            - REDIS_IP=10.5.0.6
            - REDIS_PORT=6379
        networks:
            vpc:
                ipv4_address: 10.5.0.3
    web3:
        image: demo-app:latest
        ports:
            - "5002:5000"
        environment:
            - REDIS_IP=10.5.0.6
            - REDIS_PORT=6379
        networks:
            vpc:
                ipv4_address: 10.5.0.4
    nginx-loadbalancer:
        build: nginx
        ports:
            - "81:81"
        networks:
            vpc:
                ipv4_address: 10.5.0.5

networks:
    vpc:
        driver: bridge
        ipam:
            config:
                -   subnet: 10.5.0.0/29
                    #gateway: 10.5.0.1
